'use strict';

// DDR シリーズの収録バージョンと bemaniwiki アンカー ID のマッピング。
// Constants.ts の MUSIC_VERSION 定数と値を同期すること。
// 値を追加する場合は Constants.ts の MUSIC_VERSION / MusicVersion 型も合わせて更新すること。

const MUSIC_VERSION = {
  DDR_1ST: 0,
  DDR_2ND: 1,
  DDR_3RD: 2,
  DDR_4TH: 3,
  DDR_5TH: 4,
  DDRMAX: 5,
  DDRMAX2: 6,
  DDR_EXTREME: 7,
  DDR_SUPERNOVA: 8,
  DDR_SUPERNOVA2: 9,
  DDR_X: 10,
  DDR_X2: 11,
  DDR_X3: 12,
  DDR_2013: 13,
  DDR_2014: 14,
  DDR_A: 15,
  DDR_A20: 16,
  DDR_A20PLUS: 17,
  DDR_A3: 18,
  DDR_WORLD: 19,
};

// bemaniwiki 旧曲リストのアンカー ID → MUSIC_VERSION 数値
const ANCHOR_ID_TO_VERSION = {
  AC1st: MUSIC_VERSION.DDR_1ST,
  AC2nd: MUSIC_VERSION.DDR_2ND,
  AC3rd: MUSIC_VERSION.DDR_3RD,
  AC4th: MUSIC_VERSION.DDR_4TH,
  AC5th: MUSIC_VERSION.DDR_5TH,
  ACMAX: MUSIC_VERSION.DDRMAX,
  ACMAX2: MUSIC_VERSION.DDRMAX2,
  ACEXT: MUSIC_VERSION.DDR_EXTREME,
  ACSN: MUSIC_VERSION.DDR_SUPERNOVA,
  ACSN2: MUSIC_VERSION.DDR_SUPERNOVA2,
  ACX: MUSIC_VERSION.DDR_X,
  ACX2: MUSIC_VERSION.DDR_X2,
  ACX3: MUSIC_VERSION.DDR_X3,
  AC2013: MUSIC_VERSION.DDR_2013,
  AC2014: MUSIC_VERSION.DDR_2014,
  ACA: MUSIC_VERSION.DDR_A,
  ACA20: MUSIC_VERSION.DDR_A20,
  ACA20PLUS: MUSIC_VERSION.DDR_A20PLUS,
  ACA3: MUSIC_VERSION.DDR_A3,
};

// bemaniwiki 削除曲リストの「全削除曲リスト」表で使われる、colspan 行の区切りテキスト → MUSIC_VERSION
// DDR X3 以降はアンカー ID も付与されるため ANCHOR_ID_TO_VERSION と重複するが、
// テキストのみのセクション (DDR 1st〜DDR X2) も含めて網羅する。
const DELETED_LIST_HEADING_TO_VERSION = {
  'DDR 1st': MUSIC_VERSION.DDR_1ST,
  'DDR 2ndMIX': MUSIC_VERSION.DDR_2ND,
  'DDR 3rdMIX': MUSIC_VERSION.DDR_3RD,
  'DDR 4thMIX': MUSIC_VERSION.DDR_4TH,
  'DDR 5thMIX': MUSIC_VERSION.DDR_5TH,
  DDRMAX: MUSIC_VERSION.DDRMAX,
  DDRMAX2: MUSIC_VERSION.DDRMAX2,
  'DDR EXTREME': MUSIC_VERSION.DDR_EXTREME,
  'DDR SuperNOVA': MUSIC_VERSION.DDR_SUPERNOVA,
  'DDR SuperNOVA2': MUSIC_VERSION.DDR_SUPERNOVA2,
  'DDR X': MUSIC_VERSION.DDR_X,
  'DanceDanceRevolution X2': MUSIC_VERSION.DDR_X2,
  'DanceDanceRevolution X3 VS 2ndMIX': MUSIC_VERSION.DDR_X3,
  'DanceDanceRevolution(2013)': MUSIC_VERSION.DDR_2013,
  'DanceDanceRevolution(2014)': MUSIC_VERSION.DDR_2014,
  'DanceDanceRevolution A': MUSIC_VERSION.DDR_A,
  'DanceDanceRevolution A20': MUSIC_VERSION.DDR_A20,
  'DanceDanceRevolution A20 PLUS': MUSIC_VERSION.DDR_A20PLUS,
  'DanceDanceRevolution A3': MUSIC_VERSION.DDR_A3,
  // 'DDR Solo', 'DDR Club Ver.', 'CS DDR' は MUSIC_VERSION 対象外 → マップ未登録で null 扱い
};

module.exports = { MUSIC_VERSION, ANCHOR_ID_TO_VERSION, DELETED_LIST_HEADING_TO_VERSION };
